### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by mssjliwenxu** [frankaging/BERT_LRP#2]
In train_helper.py line 612, I think the "train_features" should be "test_features" to load the segment_ids.

**Comment by frankaging** [comment]
Hi, yes. We were aware of that. Note that since we are doing single sequence labeling tasks, this was not an issue. We will make the modification soon! Otherwise; feel free to open an PR, and I will merge it! Thanks

**Comment by frankaging** [comment]
resolved by last commit. thanks for your contributions.
